'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class categoria
    Public Property Id_categoria As Integer
    Public Property descripcion_cat As String

    Public Overridable Property producto As ICollection(Of producto) = New HashSet(Of producto)

End Class
