'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalle_venta
    Public Property Id_detalle_venta As Integer
    Public Property Id_producto As Integer
    Public Property precio_unitario As Decimal
    Public Property cantidad As Integer
    Public Property subtotal As Decimal

    Public Overridable Property producto As producto
    Public Overridable Property venta As ICollection(Of venta) = New HashSet(Of venta)

End Class
