'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empleado
    Public Property Id_empleado As Integer
    Public Property nombre_empleado As String
    Public Property apellido_empleado As String
    Public Property dni_empleado As Integer
    Public Property correo_empleado As String
    Public Property telefono_empleado As Integer
    Public Property direccion_empleado As String
    Public Property usuario As String
    Public Property contraseña As String
    Public Property Id_perfil As Integer
    Public Property fecha_empleado As Date
    Public Property estado_empleado As String

    Public Overridable Property perfil As perfil
    Public Overridable Property venta As ICollection(Of venta) = New HashSet(Of venta)

End Class
