'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class perfil
    Public Property Id_perfil As Integer
    Public Property descripcion_perfil As String

    Public Overridable Property empleado As ICollection(Of empleado) = New HashSet(Of empleado)

End Class
