'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class producto
    Public Property Id_producto As Integer
    Public Property nombre_producto As String
    Public Property estado_producto As String
    Public Property precio As Decimal
    Public Property stock As Integer
    Public Property Id_categoria As Integer
    Public Property descripcion_producto As String

    Public Overridable Property categoria As categoria
    Public Overridable Property detalle_venta As ICollection(Of detalle_venta) = New HashSet(Of detalle_venta)

End Class
