'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class venta
    Public Property Id_venta As Integer
    Public Property Id_empleado As Integer
    Public Property Id_pago As Integer
    Public Property Id_cliente As Integer
    Public Property fecha As Date
    Public Property total As Decimal

    Public Overridable Property cliente As cliente
    Public Overridable Property detalle_venta As ICollection(Of detalle_venta) = New HashSet(Of detalle_venta)
    Public Overridable Property empleado As empleado
    Public Overridable Property pago As pago

End Class
